// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcfa-UnpJxH0eTUlVJBswORZQUNDkiBkM',
    appId: '1:860545872343:web:7edd852eea68e1a7811b92',
    messagingSenderId: '860545872343',
    projectId: 'doclink-ea836',
    authDomain: 'doclink-ea836.firebaseapp.com',
    databaseURL: 'https://doclink-ea836-default-rtdb.firebaseio.com',
    storageBucket: 'doclink-ea836.appspot.com',
    measurementId: 'G-DYHHG6B069',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLmJ3CpTo_ZrYk0AJB7-3PlsunCkRE-o',
    appId: '1:860545872343:android:68bd8210177fda88811b92',
    messagingSenderId: '860545872343',
    projectId: 'doclink-ea836',
    databaseURL: 'https://doclink-ea836-default-rtdb.firebaseio.com',
    storageBucket: 'doclink-ea836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIuBG1REb-Ty7XgJdzg6sYVM41mgq7AOE',
    appId: '1:860545872343:ios:54dbd16715e6e922811b92',
    messagingSenderId: '860545872343',
    projectId: 'doclink-ea836',
    databaseURL: 'https://doclink-ea836-default-rtdb.firebaseio.com',
    storageBucket: 'doclink-ea836.appspot.com',
    iosBundleId: 'com.ultrasol.doclink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIuBG1REb-Ty7XgJdzg6sYVM41mgq7AOE',
    appId: '1:860545872343:ios:ce6ef0c1ca1832e9811b92',
    messagingSenderId: '860545872343',
    projectId: 'doclink-ea836',
    databaseURL: 'https://doclink-ea836-default-rtdb.firebaseio.com',
    storageBucket: 'doclink-ea836.appspot.com',
    iosBundleId: 'com.ultrasol.doclink.RunnerTests',
  );
}
